export const scalarReferenceOptions = {
  hideDarkModeToggle: true,
  theme: 'fastify',
  showOperationId: true,
  hideClientButton: false,
  showSidebar: true,
  showDeveloperTools: 'localhost',
  showToolbar: 'localhost',
  operationTitleSource: 'summary',
  persistAuth: false,
  telemetry: true,
  externalUrls: {
    dashboardUrl: 'https://dashboard.scalar.com',
    registryUrl: 'https://registry.scalar.com',
    proxyUrl: 'https://proxy.scalar.com',
    apiBaseUrl: 'https://api.scalar.com',
  },
  layout: 'modern',
  isEditable: false,
  hideModels: false,
  documentDownloadType: 'both',
  hideTestRequestButton: false,
  hideSearch: false,
  withDefaultFonts: true,
  defaultOpenFirstTag: true,
  defaultOpenAllTags: false,
  expandAllModelSections: false,
  expandAllResponses: false,
  expandAllSchemaProperties: false,
  orderSchemaPropertiesBy: 'alpha',
  orderRequiredPropertiesFirst: true,
  modelsSectionLabel: 'Models',
  title: 'API #1',
} as const
